
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND COLUMN_OR_TABLE COMMA COMPARATOR CREATE DELETE DROP END EXECFILE FROM INDEX INSERT INTO LPAREN ON PK QUIT RPAREN SELECT STAR TABLE VALUES WHEREexpression : exp_drop\n                  | exp_select\n                  | exp_delete\n                  | exp_create\n                  | exp_insert\n                  | exp_quit\n                  | exp_execfileexp_create : CREATE TABLE COLUMN_OR_TABLE LPAREN columns RPAREN END\n                  | CREATE INDEX COLUMN_OR_TABLE ON COLUMN_OR_TABLE LPAREN COLUMN_OR_TABLE RPAREN ENDexp_drop : DROP TABLE COLUMN_OR_TABLE \n                | DROP INDEX COLUMN_OR_TABLEexp_select : SELECT STAR FROM COLUMN_OR_TABLE END\n                  | SELECT STAR FROM COLUMN_OR_TABLE exp_conditionexp_delete : DELETE FROM COLUMN_OR_TABLE END\n                  | DELETE FROM COLUMN_OR_TABLE exp_conditionexp_insert : INSERT INTO COLUMN_OR_TABLE exp_insert_lineexp_insert_line : VALUES LPAREN columns RPAREN ENDcolumns : COLUMN_OR_TABLE\n               | COLUMN_OR_TABLE COMMA columnsexp_condition : WHERE exp_all_conditions ENDexp_all_conditions : COLUMN_OR_TABLE COMPARATOR COLUMN_OR_TABLE\n                          | COLUMN_OR_TABLE COMPARATOR COLUMN_OR_TABLE AND exp_all_conditionsexp_quit : QUITexp_execfile : EXECFILE'
    
_lr_action_items = {'DROP':([0,],[9,]),'SELECT':([0,],[10,]),'DELETE':([0,],[11,]),'CREATE':([0,],[12,]),'INSERT':([0,],[13,]),'QUIT':([0,],[14,]),'EXECFILE':([0,],[15,]),'$end':([1,2,3,4,5,6,7,8,14,15,23,24,31,32,36,38,39,46,54,59,61,],[0,-1,-2,-3,-4,-5,-6,-7,-23,-24,-10,-11,-14,-15,-16,-12,-13,-20,-8,-17,-9,]),'TABLE':([9,12,],[16,20,]),'INDEX':([9,12,],[17,21,]),'STAR':([10,],[18,]),'FROM':([11,18,],[19,25,]),'INTO':([13,],[22,]),'COLUMN_OR_TABLE':([16,17,19,20,21,22,25,33,34,35,45,47,48,50,57,],[23,24,26,27,28,29,30,41,42,44,42,52,42,55,41,]),'END':([26,30,40,49,52,56,58,60,],[31,38,46,54,-21,59,61,-22,]),'WHERE':([26,30,],[33,33,]),'LPAREN':([27,37,44,],[34,45,50,]),'ON':([28,],[35,]),'VALUES':([29,],[37,]),'COMPARATOR':([41,],[47,]),'RPAREN':([42,43,51,53,55,],[-18,49,56,-19,58,]),'COMMA':([42,],[48,]),'AND':([52,],[57,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,],[1,]),'exp_drop':([0,],[2,]),'exp_select':([0,],[3,]),'exp_delete':([0,],[4,]),'exp_create':([0,],[5,]),'exp_insert':([0,],[6,]),'exp_quit':([0,],[7,]),'exp_execfile':([0,],[8,]),'exp_condition':([26,30,],[32,39,]),'exp_insert_line':([29,],[36,]),'exp_all_conditions':([33,57,],[40,60,]),'columns':([34,45,48,],[43,51,53,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> exp_drop','expression',1,'p_expression_start','interpreter.py',116),
  ('expression -> exp_select','expression',1,'p_expression_start','interpreter.py',117),
  ('expression -> exp_delete','expression',1,'p_expression_start','interpreter.py',118),
  ('expression -> exp_create','expression',1,'p_expression_start','interpreter.py',119),
  ('expression -> exp_insert','expression',1,'p_expression_start','interpreter.py',120),
  ('expression -> exp_quit','expression',1,'p_expression_start','interpreter.py',121),
  ('expression -> exp_execfile','expression',1,'p_expression_start','interpreter.py',122),
  ('exp_create -> CREATE TABLE COLUMN_OR_TABLE LPAREN columns RPAREN END','exp_create',7,'p_expression_create','interpreter.py',125),
  ('exp_create -> CREATE INDEX COLUMN_OR_TABLE ON COLUMN_OR_TABLE LPAREN COLUMN_OR_TABLE RPAREN END','exp_create',9,'p_expression_create','interpreter.py',126),
  ('exp_drop -> DROP TABLE COLUMN_OR_TABLE','exp_drop',3,'p_expression_drop','interpreter.py',141),
  ('exp_drop -> DROP INDEX COLUMN_OR_TABLE','exp_drop',3,'p_expression_drop','interpreter.py',142),
  ('exp_select -> SELECT STAR FROM COLUMN_OR_TABLE END','exp_select',5,'p_expression_select','interpreter.py',160),
  ('exp_select -> SELECT STAR FROM COLUMN_OR_TABLE exp_condition','exp_select',5,'p_expression_select','interpreter.py',161),
  ('exp_delete -> DELETE FROM COLUMN_OR_TABLE END','exp_delete',4,'p_expression_delete','interpreter.py',172),
  ('exp_delete -> DELETE FROM COLUMN_OR_TABLE exp_condition','exp_delete',4,'p_expression_delete','interpreter.py',173),
  ('exp_insert -> INSERT INTO COLUMN_OR_TABLE exp_insert_line','exp_insert',4,'p_expression_insert','interpreter.py',181),
  ('exp_insert_line -> VALUES LPAREN columns RPAREN END','exp_insert_line',5,'p_expression_insert_line','interpreter.py',191),
  ('columns -> COLUMN_OR_TABLE','columns',1,'p_expression_columns','interpreter.py',194),
  ('columns -> COLUMN_OR_TABLE COMMA columns','columns',3,'p_expression_columns','interpreter.py',195),
  ('exp_condition -> WHERE exp_all_conditions END','exp_condition',3,'p_expression_condition','interpreter.py',200),
  ('exp_all_conditions -> COLUMN_OR_TABLE COMPARATOR COLUMN_OR_TABLE','exp_all_conditions',3,'p_expression_all_conditions','interpreter.py',203),
  ('exp_all_conditions -> COLUMN_OR_TABLE COMPARATOR COLUMN_OR_TABLE AND exp_all_conditions','exp_all_conditions',5,'p_expression_all_conditions','interpreter.py',204),
  ('exp_quit -> QUIT','exp_quit',1,'p_expression_quit','interpreter.py',214),
  ('exp_execfile -> EXECFILE','exp_execfile',1,'p_expression_execfile','interpreter.py',220),
]
